# Generated by Django 4.1.6 on 2023-02-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('website_url', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('banner_pic', models.CharField(max_length=50)),
                ('cancellation_policy', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdmytableapi.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_styles', to='holdmytableapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('shape', models.CharField(max_length=25)),
                ('is_reserved', models.BooleanField()),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('reservable', models.BooleanField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='holdmytableapi.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('content', models.CharField(max_length=240)),
                ('image_url', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reviews', to='holdmytableapi.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdmytableapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_images', to='holdmytableapi.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdmytableapi.user'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdmytableapi.style'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(max_length=240)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_reservations', to='holdmytableapi.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holdmytableapi.user')),
            ],
        ),
    ]
