# Generated by Django 4.1.6 on 2023-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmytableapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_tier',
            field=models.CharField(default='$$$$', max_length=4),
            preserve_default=False,
        ),
    ]
