# Generated by Django 4.1.6 on 2023-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmytableapi', '0002_restaurant_price_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bio',
            field=models.CharField(default='this is a bio', max_length=500),
            preserve_default=False,
        ),
    ]
