# Generated by Django 4.1.6 on 2023-02-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmytableapi', '0004_remove_table_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_policy',
            field=models.CharField(default='please give 24 hour notice', max_length=240),
            preserve_default=False,
        ),
    ]
