# Generated by Django 4.1.6 on 2023-02-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdmytableapi', '0004_reservation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
