# Generated by Django 4.1.6 on 2023-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdmytableapi', '0006_reservation_guests_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='_reserved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
