# Generated by Django 4.1.6 on 2023-02-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holdmytableapi', '0007_table__reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='_reserved',
        ),
    ]
